# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestMatchesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('home_name', models.CharField(max_length=30)),
                ('away_name', models.CharField(max_length=30)),
                ('kick_off_time', models.DateTimeField()),
            ],
        ),
    ]
