# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestMatchesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('match_id', models.IntegerField(default=-1)),
                ('home_name', models.CharField(default=None, max_length=20)),
                ('away_name', models.CharField(default=None, max_length=20)),
                ('kick_off_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatestMatchesDataStaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('match_id', models.IntegerField(default=-1)),
                ('home_name', models.CharField(default=None, max_length=20)),
                ('away_name', models.CharField(default=None, max_length=20)),
                ('kick_off_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('match_id', models.IntegerField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
            ],
        ),
    ]
