# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchUpdater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestmatchesdata',
            name='away_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='latestmatchesdata',
            name='home_name',
            field=models.CharField(max_length=20),
        ),
    ]
