# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchUpdater', '0002_auto_20180704_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestmatchesdata',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
