# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatchUpdater', '0003_latestmatchesdata_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestMatchesDataStaging',
            fields=[
                ('latestmatchesdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MatchUpdater.LatestMatchesData')),
            ],
            bases=('MatchUpdater.latestmatchesdata',),
        ),
    ]
