# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchUpdater', '0004_latestmatchesdatastaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('match_id', models.IntegerField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='latestmatchesdata',
            name='match_id',
            field=models.IntegerField(default=-1),
        ),
    ]
